### ISSUE TITLE
The site does not build

### ISSUE THREAD

**Issue by tnwae** [tnwae/rt38.net#10]
This smells like trouble with the Haml templates, and I may have to switch to HTML to make my life easier, or include build-out of the templates as a deployment prereq.

To suss out any possible Haml issues, I manually built each template and partial, and everything worked.  Jekyll is choking on the main site template, which was the last one to be modified (in 98f6059).

Jekyll vomited a huge error (with backtrace) onto my xterm; it follows.

```
Configuration file: /home/wae/rt38.net/_config.yml
            Source: /home/wae/rt38.net
       Destination: /home/wae/rt38.net/_site
      Generating... 
  Liquid Exception: undefined method `data' for #<Jekyll::HamlPartialTag:0x00000003b0cfb8> in _layouts/default.html
/home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-haml-0.1.2/lib/jekyll-haml/tags/haml_partial.rb:33:in `rescue in block in render': undefined method `data' for #<Jekyll::HamlPartialTag:0x00000003b0cfb8> (NoMethodError)
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-haml-0.1.2/lib/jekyll-haml/tags/haml_partial.rb:30:in `block in render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-haml-0.1.2/lib/jekyll-haml/tags/haml_partial.rb:24:in `chdir'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-haml-0.1.2/lib/jekyll-haml/tags/haml_partial.rb:24:in `render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/block.rb:109:in `block in render_all'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `each'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/block.rb:96:in `render_all'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/block.rb:82:in `render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/template.rb:128:in `render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/liquid-2.6.3/lib/liquid/template.rb:138:in `render!'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:106:in `render_liquid'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:205:in `render_all_layouts'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/convertible.rb:239:in `do_layout'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/post.rb:261:in `render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/site.rb:298:in `block in render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `each'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/site.rb:297:in `render'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/site.rb:51:in `process'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/command.rb:28:in `process_site'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:56:in `build'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:34:in `process'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/wae/.rvm/gems/ruby-head@blogging/gems/jekyll-2.5.3/bin/jekyll:20:in `<top (required)>'
        from /home/wae/.rvm/gems/ruby-head@blogging/bin/jekyll:23:in `load'
        from /home/wae/.rvm/gems/ruby-head@blogging/bin/jekyll:23:in `<main>'
        from /home/wae/.rvm/gems/ruby-head@blogging/bin/ruby_executable_hooks:15:in `eval'
        from /home/wae/.rvm/gems/ruby-head@blogging/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by tnwae** [comment]
Subbing the Haml output into `default.html` did not change anything: Jekyll still craps itself at the same place.

**Comment by tnwae** [comment]
De-Hamlizing the footer markup and subbing into the expanded `default.html` revealed the problem: I had forgotten to update Socializer for 500px.  :blush:

**Comment by JangoSteve** [comment]
If anyone else comes across this, I was also getting this error. Turned out to be one of my attribute tags in haml with a typo:

```
%a{:href > "/some-link"} Link
```

Notice the `>` instead of `=>`. This was causing the same `undefined method 'data'` error above.
